### ISSUE TITLE
Duplicated sequence names displays nondescript error and breaks execution for current file

### ISSUE THREAD

**Issue by josephnobes-stfc** [stfc-aeg/odin-sequencer#35]
* Command Sequencer version: 0.1.0
* Python version: 3.7.6
* Operating System: Linux

### Description

Created a sequence file with duplicated sequence name appearances in the `provides` list:

```python
provides = [
    'testfunc',
    'testfunc'
    ]

def testfunc():
    print("Hello, world")
```

### What I Did

The sequencer will load fine the first time but on the first reload with the duplicated value, the following error is displayed in the UI:

>PUT request to api/0.1/odin-sequencer/ failed with status 500
>To load the missing sequences, first resolve the errors and then click the Reload button

With this error in the log:
```python
[E 220804 14:35:32 web:1670] Uncaught exception PUT /api/0.1/odin_sequencer/ (192.168.100.1)
    HTTPServerRequest(protocol='http', host='192.168.100.2:8888', method='PUT', uri='/api/0.1/odin_sequencer/', version='HTTP/1.1', remote_ip='192.168.100.1')
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/lib/python3.7/site-packages/odin/http/handlers/async_api.py", line 60, in put
        response = adapter.put(path, self.request)
      File "/usr/lib/python3.7/site-packages/odin/adapters/adapter.py", line 225, in wrapper
        return func(_self, path, request)
      File "/usr/lib/python3.7/site-packages/odin/adapters/adapter.py", line 285, in wrapper
        return func(_self, path, request)
      File "/usr/lib/python3.7/site-packages/odin_sequencer/adapter.py", line 73, in put
        self.command_sequencer.set(path, data)
      File "/usr/lib/python3.7/site-packages/odin_sequencer/command_sequencer.py", line 93, in set
        self.param_tree.set(path, data)
      File "/usr/lib/python3.7/site-packages/odin/adapters/base_parameter_tree.py", line 307, in set
        merged = self._merge_tree(merge_child, data, path)
      File "/usr/lib/python3.7/site-packages/odin/adapters/base_parameter_tree.py", line 482, in _merge_tree
        update[k] = self._merge_tree(node[k], v, cur_path + k + '/')
      File "/usr/lib/python3.7/site-packages/odin/adapters/base_parameter_tree.py", line 502, in _merge_tree
        self._set_node(node, new_data)
      File "/usr/lib/python3.7/site-packages/odin/adapters/base_parameter_tree.py", line 523, in _set_node
        node.set(data)
      File "/usr/lib/python3.7/site-packages/odin/adapters/base_parameter_tree.py", line 163, in set
        response = self._set(value)
      File "/usr/lib/python3.7/site-packages/odin_sequencer/command_sequencer.py", line 159, in set_reload
        self._reload()
      File "/usr/lib/python3.7/site-packages/odin_sequencer/command_sequencer.py", line 180, in _reload
        self.manager.reload(file_paths=modified_module_paths, resolve=False)
      File "/usr/lib/python3.7/site-packages/odin_sequencer/manager.py", line 307, in reload
        self._unload([file_path.stem for file_path in file_paths])
      File "/usr/lib/python3.7/site-packages/odin_sequencer/manager.py", line 326, in _unload
        delattr(self, provided)
    AttributeError: testfunc
```

From this point, no sequences can be executed from that specific file (they do nothing when called). Other files can run sequences without issue.

In addition, the error can be reproduced starting with no duplicate entries, but adding a duplicate and clicking 'Reload' twice. The error will only appear after the second click, once the manager already has the double entry loaded by the first click.

**Comment by josephnobes-stfc** [comment]
This check already exists in the manager code:

```python
if any(seq_name in val for val in self.provides.values()):
                    raise CommandSequenceError(
                        "Unable to load sequence '{}' from module '{}' as a sequence with the "
                        "same name has already being registered".format(seq_name, module_name)
                    )
```

However, it checks against `self.provides` (which hasn't been populated at this time) rather than `provides`.
